name: Rust github action
author: Ilya Selivanov
description: Simple tests for Rust github action
inputs:
  args:
    description: Arguments passed to the action
    required: true
    default: ""
outputs:
  results:
    description: The results from calling the action
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.args }}
